pgtest/pgtest/urls.py
# """
# URL configuration for pgtest project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path, include
# from testdb import views

# #hello
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('testdb/', include('testdb.urls'))
# ]


from django.contrib import admin
from django.urls import path, include
from testdb import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('testdb/',include('testdb.urls')),
    # path('', views.BusinessView.as_view(), name='BusinessView'),
    path('addBusiness/', views.add_business, name='add_business'),
    path('emp', views.emp),  
    path('show',views.show), 
    path('',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

pgtest/testdb/urls.py
# from django.urls import path
# from . import views

# #url configuration
# urlpatterns = [
#     path('hello/', views.say_hello)
# ]
from django.urls import path, include
from .views import emp, add_business

urlpatterns = [
    path('', emp, name='index'),
    path('addBusiness/', add_business, name='add_business_business'),
]

pgtest/testdb/models.py
from django.db import models
# Create your models here.
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15) 
    lat = models.DecimalField(max_digits=19, decimal_places=10)
    lng = models.DecimalField(max_digits=19, decimal_places=10) 
    class Meta:  
        db_table = "employee" 

        
class Banks(models.Model):
    gid = models.AutoField(primary_key=True)
    code = models.SmallIntegerField(blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    lat = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    lng = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    geom = models.TextField(blank=True, null=True)  # This field type is a guess.

    class Meta:
        managed = False
        db_table = 'banks' 

pgtest/testdb/forms.py
from django import forms  
from testdb.models import Employee

class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"

pgtest/testdb/views.py
# from django.shortcuts import render
# from django.http import HttpResponse
# from .models import Banks

# # # Create your views here.
# # def index (request):
# #     return render (request, 'templates/testdb/index.html')
# def say_hello(request):
#     return render(request, 'index.html')
# def index (request):
# #Access all rows of banks table
#     banks = Banks.objects.all()
#     return render (request, 'testdb/index.html', {'banks': banks})
from django.shortcuts import render, redirect  
from testdb.forms import EmployeeForm
from testdb.models import Employee  

def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  # add indentation here
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})
  
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  
def add_business(request):
    # your view logic here
    return render(request, 'add_business.html')

pgtest/testdb/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link rel="stylesheet" href="../static/css/style.css"/>
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <!-- leaflet CSS -->
  <link
    rel="stylesheet"
    href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
    integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
    crossorigin=""
  />
  <!-- Make sure you put this AFTER Leaflet's CSS -->
  <script
    src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
    integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
    crossorigin=""
  ></script> 
    <style>
      #map {
        height: 80vh;
        width: 40%;
        margin-left: auto;
        margin-right: 0;
        border: 1px solid black;
        margin: 4px;
      }
      .left {
        margin-right: auto;
        margin-left: 0;
        width: 40%;
        border: 1px solid black;
      }
    </style>
</head>  
<body> 
  <div class="row">
    <div class="col-6"> 
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Location Latitude:</label>  
    <div class="col-sm-4">  
        <input type="number" step="any" name="lat" id="id_elat" required maxlength="100" value="{{ employee.lat }}" />  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Location Longitude:</label>  
    <div class="col-sm-4">  
        <input type="number" step="any" name="lng" id="id_elng" required maxlength="100" value="{{ employee.lng }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</div>
<div id="map" class="col-5"></div>
</div>

<script>
  var map = L.map("map").setView([31.505, 74.09], 5);
  var OpenStreetMap_Mapnik = L.tileLayer(
    "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    {
      maxZoom: 19,
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }
  ).addTo(map);
var lat = document.getElementById('id_elat').value
var lng = document.getElementById('id_elng').value
  var marker = L.marker();
  if (lat > 0){
    marker
    .setLatLng([lat,lng])
    .addTo(map);

  }
  
function onMapClick(e) {
marker
    .setLatLng(e.latlng)
    .addTo(map);
    console.log(e.latlng, 'lat lng');
    document.getElementById('id_elat').value = e.latlng.lat.toFixed(10)
    document.getElementById('id_elng').value = e.latlng.lng.toFixed(10)
}

map.on('click', onMapClick);

  // "{% for item in banks %}"
  //       var marker = L.marker(["{{item.lng}}","{{item.lat}}"]).bindPopup("<strong><input type='text' value={{item.name}}></input></strong><br/>{{item.code}}").addTo(map).on('popupopen', function (e) {
  //               // console.log(e.popup.getContent())
  //       });;
  // "{% endfor %}"
</script>
</body>  
</html>  

pgtest/testdb/templates/index.html
{% comment %} And set up basic html structure file.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossorigin=""/>

   <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
 integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
 crossorigin=""></script>


    
    
    <title>Banks Map</title>
    <style>
        #map {
            height: 97vh;
        }
     </style>
    
</head>
<body>
    <div id="map"></div>
    <script>
        var map = L.map('map').setView([31.505, 74.09], 5);
        var OpenStreetMap_Mapnik = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
"{% for item in banks %}"   
            var marker = L.marker(["{{item.lng}}","{{item.lat}}"]).bindPopup("<strong>{{item.name}}</strong><br/>{{item.code}}").addTo(map).on('popupopen', function (e) {
                    // console.log(e.popup.getContent())
            });;
"{% endfor %}"
    </script>

        
</body>
</html> {% endcomment %}



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    <link rel="stylesheet" href="../static/css/style.css" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <!-- leaflet CSS -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin=""
    />
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script
      src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
      integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
      crossorigin=""
    ></script>
    <style>
      #map {
        height: 80vh;
        width: 40%;
        margin-left: auto;
        margin-right: 0;
        border: 1px solid black;
        margin: 4px;
      }
      .left {
        margin-right: auto;
        margin-left: 0;
        width: 40%;
        border: 1px solid black;
      }
    </style>
  </head>
  <body>
    <div class="row">
    <div class="col-6">
        <form method="POST" class="post-form " action="/emp">
            {% csrf_token %}
            <div class="container">
              <br />
              <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                  <h3>Enter Details</h3>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Id:</label>
                <div class="col-sm-4">{{ form.eid }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Name:</label>
                <div class="col-sm-4" id="lat">{{ form.ename }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email:</label>
                <div class="col-sm-4">{{ form.eemail }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">{{ form.econtact }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">Location Latitude:</label>
                <div class="col-sm-4">{{ form.lat }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-2 col-form-label">Location Longitude:</label>
                <div class="col-sm-4">{{ form.lng }}</div>
              </div>
              <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div id="map" class="col-5"></div>
    </div>
        <script>
          var map = L.map("map").setView([31.505, 74.09], 5);
          var OpenStreetMap_Mapnik = L.tileLayer(
            "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
            {
              maxZoom: 19,
              attribution:
                '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            }
          ).addTo(map);
    
          var marker = L.marker();
    
    function onMapClick(e) {
        marker
            .setLatLng(e.latlng)
            .addTo(map);
            console.log(e.latlng, 'lat lng');
            document.getElementById('id_lat').value = e.latlng.lat.toFixed(10)
            document.getElementById('id_lng').value = e.latlng.lng.toFixed(10)
    }
    
    map.on('click', onMapClick);
    
          // "{% for item in banks %}"
          //       var marker = L.marker(["{{item.lng}}","{{item.lat}}"]).bindPopup("<strong><input type='text' value={{item.name}}></input></strong><br/>{{item.code}}").addTo(map).on('popupopen', function (e) {
          //               // console.log(e.popup.getContent())
          //       });;
          // "{% endfor %}"
        </script>
      </body>
    </html>
    

pgtest/testdb/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
    <link rel="stylesheet" href="../static/css/style.css"/>
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <!-- leaflet CSS -->
  <link
    rel="stylesheet"
    href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
    integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
    crossorigin=""
  />
  <!-- Make sure you put this AFTER Leaflet's CSS -->
  <script
    src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
    integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
    crossorigin=""
  ></script>
  <style>
    #map {
      height: 60vh;
    
      margin-left: auto;
      margin-right: 0;
      border: 1px solid black;
      margin: 4px;
    }
</style>
</head>  
<body>
    <div style="margin:5px"></div>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Employee Latitude</th>  
        <th>Employee Longitude</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td> 
        <td>{{ employee.lat }}</td>  
        <td>{{ employee.lng }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  

<div id="map"></div>
</div>
<script>
    var map = L.map("map").setView([31.505, 74.09], 5);
    var OpenStreetMap_Mapnik = L.tileLayer(
      "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      {
        maxZoom: 19,
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      }
    ).addTo(map);
        "{% for item in employees %}"
            var marker = L.marker(["{{item.lat}}","{{item.lng}}"]).bindPopup("<strong>{{item.ename}}</strong><br/>Contact: {{item.econtact}}").addTo(map).on('popupopen', function (e) {
                    // console.log(e.popup.getContent())
            });;
      "{% endfor %}"
    </script>
</body>  
</html>  